const $=s=>document.querySelector(s);const sessionGet=k=>{try{return sessionStorage.getItem(k)||''}catch{return''}},sessionSet=(k,v)=>{try{sessionStorage.setItem(k,v)}catch{}},sessionRemove=k=>{try{sessionStorage.removeItem(k)}catch{}};let profiles=[],code=sessionGet('teacherDashboardCode');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2500);}
function fmt(value){const d=new Date(value||0);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-SG',{dateStyle:'short',timeStyle:'short'});}
async function load(){
  let data=null;
  try{const r=await fetch('/api/progress',{headers:{'x-teacher-code':code}});if(r.ok)data=await r.json();}
  catch{}
  if(!data){
    if(code!=="FNDMSMXMT5")throw new Error('教师代码不正确。');
    try{profiles=Object.values(JSON.parse(localStorage.getItem('oralAppProfilesV4')||'{}'));}catch{profiles=[];}
    data={updatedAt:new Date().toISOString()};
    $('#loginMessage').textContent='试用预览：这里只显示同一浏览器中保存的学生档案。正式云端看板会汇总不同学生设备。';
  }else{profiles=data.profiles||[];$('#loginMessage').textContent='';}
  sessionSet('teacherDashboardCode',code);$('#loginPanel').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#updatedAt').textContent=`最后更新：${fmt(data.updatedAt)}`;renderFilters();render();
}
function filtered(){const q=$('#searchBox').value.trim().toLowerCase(),cls=$('#classFilter').value;return profiles.filter(p=>(!cls||p.className===cls)&&(!q||`${p.name} ${p.className}`.toLowerCase().includes(q)));}
function renderFilters(){const current=$('#classFilter').value,classes=[...new Set(profiles.map(p=>p.className).filter(Boolean))].sort();$('#classFilter').innerHTML='<option value="">所有班级</option>'+classes.map(c=>`<option ${c===current?'selected':''}>${esc(c)}</option>`).join('');}
function render(){const list=filtered();$('#studentCount').textContent=list.length;$('#readingCount').textContent=list.reduce((n,p)=>n+(p.reading?.length||0),0);$('#oralCount').textContent=list.reduce((n,p)=>n+(p.conversation?.length||0),0);$('#starCount').textContent=list.reduce((n,p)=>n+(p.stars||0),0);$('#studentRows').innerHTML=list.map((p,i)=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.className)}</td><td>${p.reading?.length||0}</td><td>${p.conversation?.length||0}</td><td>${p.stars||0}</td><td>${fmt(p.lastAccessed)}</td><td><button class="view-btn" data-view="${profiles.indexOf(p)}">查看</button></td></tr>`).join('');$('#emptyState').classList.toggle('hidden',Boolean(list.length));}
function showDetail(i){const p=profiles[i];if(!p)return;$('#detailName').textContent=`${p.name} · ${p.className}`;$('#detailStats').innerHTML=`<span>📖 朗读 ${p.reading?.length||0}</span><span>💬 口语 ${p.conversation?.length||0}</span><span>⭐ ${p.stars||0}</span><span>最后练习 ${fmt(p.lastAccessed)}</span>`;$('#detailHistory').innerHTML=(p.history||[]).length?(p.history||[]).slice(0,15).map(h=>`<div class="history-item"><span>${h.type==='reading'?'📖':'💬'} ${esc(h.title)}</span><span>${h.score}% · ${esc(h.date||fmt(h.iso))}</span></div>`).join(''):'<p>还没有练习记录。</p>';$('#detailPanel').classList.remove('hidden');$('#detailPanel').scrollIntoView({behavior:'smooth'});}
function csv(){const rows=[['Name','Class','Reading completed','Oral completed','Stars','Last accessed'],...filtered().map(p=>[p.name,p.className,p.reading?.length||0,p.conversation?.length||0,p.stars||0,p.lastAccessed||''])];const out=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+out],{type:'text/csv'}));a.download='chinese-oral-progress.csv';a.click();URL.revokeObjectURL(a.href);}
$('#loginBtn').onclick=async()=>{code=$('#teacherCode').value.trim();$('#loginMessage').textContent='正在读取……';try{await load();$('#loginMessage').textContent='';}catch(e){$('#loginMessage').textContent=e.message;}};$('#teacherCode').value=code;$('#teacherCode').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click();});$('#refreshBtn').onclick=()=>load().then(()=>toast('已刷新')).catch(e=>toast(e.message));$('#searchBox').oninput=render;$('#classFilter').onchange=render;$('#studentRows').onclick=e=>{const b=e.target.closest('[data-view]');if(b)showDetail(Number(b.dataset.view));};$('#closeDetail').onclick=()=>$('#detailPanel').classList.add('hidden');$('#exportBtn').onclick=csv;if(code)load().catch(()=>sessionRemove('teacherDashboardCode'));
